### ISSUE TITLE
A Feedback for tweening RectTransform Anchors

### ISSUE THREAD

**Issue by digiwombat** [Juce-Assets/Juce-Feedbacks#14]
Hey again.

So if you want to do resolution independent UI tweening, you need to tween anchors rather than anchored positions or anything else. I wrote an Anchor tweener which takes inputs for the Anchor Min numbers and calculates the Anchor Max based on the RectTransform's values then tweens them.

https://gist.github.com/digiwombat/21ec82fa92c258d2bc572ecb22263e86

There's a gist with it. Feel free to roll it into the repo proper! Sorry for being too lazy to bother doing a pull request. :D

**Comment by Guillemsc** [comment]
Hey @digiwombat, thanks for taking the time to report all the bugs and suggestions! I really helps me improve the tool :)
During this week I will look into every one of them and start fixing/improving.

**Comment by digiwombat** [comment]
No worries. Thanks for the tools, man. Hopefully when I get some free time I can dig in a bit more and maybe add some more stuff with a proper pull request. Haha.

**Comment by Guillemsc** [comment]
@digiwombat Is there a particular reason why you use the AnchorMin as the base, and then you get the AnchorMax with the offset? How do you normally use this? Doesn't it make more sense that the tweened Anchor position is the center between the Min and the Max? 

`Example: If you have AnchorMin of x:0 y:0, and AnchorMax of x:1 y:1, the position is x:0.5 y:0.5. So if you set the position x:0, y:0 on the feedback, the final values are AnchorMin of x:-0.5 y:-0.5, and AnchorMax of x:0.5 y:0.5. ` 

I don't know if what I'm saying makes sense. It's just a matter of usability, and how to make it as clear as possible.

**Comment by digiwombat** [comment]
The short version is I just adapted logic of this Unity Screen Transition page: https://docs.unity3d.com/2020.1/Documentation/Manual/HOWTO-UIScreenTransition.html

I think ideally you'd be able to set Min and Max values independently (which is how must things handle it and allows you to do more complex shape stuff). However, I mostly just arbitrarily picked a value to use as my baseline (the Min) and used the calculation as a way to make sure the shape was maintained over the tween. The reason I did that was because I wasn't sure how to get clear labeling for the two different Vector2s with your attributes and would ideally have done a custom layout for Anchor values to begin with but I'm the only programmer on my game so I went with the quick and dirty option.

Any version that doesn't allow editing of both Min and Max values independently is going to be confusing and I'd definitely recommend allowing the editing of both and having a UI which makes it clear what you're editing.

**Comment by Guillemsc** [comment]
What do you think about two different feedbacks, one for min and another for max? Or it would be better to have both combined on one feedback?

**Comment by digiwombat** [comment]
It should definitely be both in one Feedback, I think since the most common use case is going to be tweening both min and max to maintain the same size of RectTransform. The other, less common, use case could be achieved by using two anyway, so the people who need it could use it that way, whereas I'd guess 99% of Anchor-based tweens are just going to be moving something onto the screen or off of the screen, which requires tweening Min and Max at the same ratio for Stretched canvases to keep the size constant.

**Comment by Guillemsc** [comment]
Closing this. New features are available on the [last release](https://github.com/Juce-Assets/Juce-Feedbacks/releases/tag/1.3.0). Thanks for your suggestions, they have been very useful :)
Don't hesitate on reaching again if you find more problems/suggestions.
