### ISSUE TITLE
Make Target Settable in FeedbacksPlayerPlayFeedback

### ISSUE THREAD

**Issue by digiwombat** [Juce-Assets/Juce-Feedbacks#18]
Hey! Me again. :D

I have a dynamic state machine transition where I'm basically running a Feedback for hiding one menu and then showing another. Rather than create feedbacks for every possible transition, I was hoping to create generic "HideInventory" and "ShowMap" transitions which play one after another in a feedback player play script. The problem I ran into was that FeedbacksPlayerPlayFeedback.Target is just a lambda to the private FeedbacksPlayerPlayFeedback.target field with no setter.

Obviously, that makes me cry. Haha.

Can we make the target field settable at runtime, either by making it public or switching Target to be a Getter/Setter?

For my local versions, I've turned it to a Getter/Setter since that seemed to be in line with how duration is being set:

```
public FeedbacksPlayer Target
{
	get => target;
	set => target = value;
}
```

Let me know if there's any reason this value shouldn't be changed.

**Comment by Guillemsc** [comment]
That's actually a bug! For some reason I forgot to add the set to some feedbacks. 
You can see how UIAlphaFeedback has the proper implementation D:
![image](https://user-images.githubusercontent.com/17142208/102806447-298e3e80-43bd-11eb-96ef-692f15125c83.png)

I will fix this, thanks for bringing up this big issue!

**Comment by Guillemsc** [comment]
Closing this. Fixes are available on a new [release](https://github.com/Juce-Assets/Juce-Feedbacks/releases/tag/1.4.0). 
Thanks again for the help :D 👍

**Comment by Guillemsc** [comment]
The new release also contains a new FeedbacksPlayerKillAndResetFeedback, to reset target feedbacks.
