### ISSUE TITLE
Option to Use UnscaledDeltaTime

### ISSUE THREAD

**Issue by digiwombat** [Juce-Assets/Juce-Feedbacks#19]
Hey again.

Amazing I'm just now noticing this, but most of the feedbacks I've checked rely on scaled Time.deltaTime rather than the Time.unscaledDeltaTime.

This isn't ideal since I set my timeScale to 0 when opening UIs and that causes the Feedbacks to freeze in place.

I'd greatly appreciate an Ignore Timescale checkbox on the Juce Feedbacks script so that the tweens will use Time.unscaledDeltaTime and play even when my TimeScale is set to 0.

**Comment by Guillemsc** [comment]
Yes, that is something that I was planning to do, but I forgot about it haha. I'm working on it :)

**Comment by Guillemsc** [comment]
This is fixed on the next release. 
You can find the documentation for the way it works [here](https://github.com/Juce-Assets/Juce-Feedbacks/wiki/Time-scale).
As always, thanks for the feedback @digiwombat
