### ISSUE TITLE
Contributions and package distribution

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [Juce-Assets/Juce-Feedbacks#2]
Hi there, I enjoyed seeing your library in-action on Reddit and Twitter recently and was wondering what kind of contributions to this library you might be potentially looking for, if any. I have experience with maintaining several of my own open-source libraries for Unity on Github and would love to help!

For example, one topic I'd like to help assist with is creating an openupm package version of this library so that it's easier for users to add to their project. This can help to make resolving dependencies much easier and near-effortless for your users and can make it easier for them to use without needing to know git and/or manage  submodules.

**Comment by Guillemsc** [comment]
Hi @jeffcampbellmakesgames, thanks for reaching out! 
As for the kind of contributions, anything that improves the tool is very welcome :)

I'm not familiar with openupm, but I can see the benenfits.  
My intention is to release this as a free package on the Asset Store, but keep in mind it's still in development.

I'm the first time I create a unity asset / open-source tool, so any help is appreciated.

**Comment by jeffcampbellmakesgames** [comment]
The Asset Store is great; a lot of people can see it there and get introduced to your library. Releasing your library as a package can make it even easier for users to be able to add it to their projects and enables you to be able to put out updates/fixes quicker without waiting for approval through the store. [OpenUpm](https://openupm.com/) makes it even easier in that their command-line tools make it so that when they would add something like Juce-Feedbacks to their repository it would also add all the dependencies like Juce-Tween and Juce-Utils.

What you'd want to look at if you want to add your libraries to OpenUPM is to:
* Make sure you have a branch where library contents and the `package.json` for that library includes any dependent packages in it. This enables other developers when using OpenUPM and as long as those dependent packages are also on OpenUPM to automatically resolve them. For you, this would likely be your existing master branch as your repository is setup with the library/package contents at the root, but it could be any branch. 
    * I have a slightly different setup than you do where all of my open-source libraries include their own Unity project, documentation, other files for developing the library on the default branch and I publish the library's package contents on an orphaned side branch that OpenUPM is set to use. This has the dual advantage for me of always having an independent, dedicated, fixed Unity project to develop in that others can easily grab and jump in to start tweaking things while my package source is isolated/siloed from any development projects or tools. You can find an example of that [here](https://github.com/jeffcampbellmakesgames/Entitas-Redux).
* Submit your package on openupm [here](https://openupm.com/packages/add/). The way it works is that once you've submitted the package once it will track changes to the branch you've specified and make a new package available every time a new SemVer tag (like `v1.0.0` or `v1.2.1`) is added to that git branch. You would want to repeat this process for Juce-Feedbacks and then for any of it's dependencies like Juce-Tween or Juce-Utils.
* Once that's done successfully (you should get notifications on GitHub when this has completed), a user should be able to add your library to their Unity project by opening a terminal to their Unity project and typing `openupm add `com.juce.feedbacks`. Super easy and accessible!

**Comment by Guillemsc** [comment]
Hey @jeffcampbellmakesgames! Thanks for all the info, I really appreciate it. I will try to set up everything with OpenUPM when the library is a bit more finished and ready to publish. I've already done some tests with OpenUPM and it's not difficult to set up, so that's nice, since I'm only one person and I need to spend my time carefully.
Thanks again for taking the time to write all this useful info :)

**Comment by jeffcampbellmakesgames** [comment]
> Hey @jeffcampbellmakesgames! Thanks for all the info, I really appreciate it. I will try to set up everything with OpenUPM when the library is a bit more finished and ready to publish. I've already done some tests with OpenUPM and it's not difficult to set up, so that's nice, since I'm only one person and I need to spend my time carefully.
> Thanks again for taking the time to write all this useful info :)

No problem! Glad to help :)
