### ISSUE TITLE
Missing scripts in example content

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [Juce-Assets/Juce-Feedbacks#3]
**Describe the bug**
I have a development project for testing, analyzing Juce Feedbacks that has the Feedbacks, Tween, and Utils submodules cloned to a Unity project. There appears to be missing scripts on several objects in the example content that may or may not be causing some of the demo content to not work as expected. Most of the Feedbacks specific functionality is working as intended, but I am unsure if there is other missing demo functionality from these other scripts.

**To Reproduce**
1. Clone the development repository here with submodules (https://github.com/jeffcampbellmakesgames/Juce-Dev).
2. Open the Unity project contained within.
3. Open any of the example content scenes in the Feedback submodules
4. Look at various gameobjects to see if scripts are missing. I see them most often on the MainCamera object, but there are other ones. You may be able to use something like this (https://wiki.unity3d.com/index.php/FindMissingScripts) to find them all programmatically.

**Expected behavior**
All scripts should be present.

**Screenshots**
![image](https://user-images.githubusercontent.com/1663648/99073262-983cd880-2583-11eb-8692-020954806404.png)
![image](https://user-images.githubusercontent.com/1663648/99073366-c3272c80-2583-11eb-98cd-d3d217e56288.png)

**Desktop (please complete the following information):**
 - OS: Windows
- Unity: 2019.4.11f1

**Smartphone (please complete the following information):**
- Not applicable

**Additional context**
It's possible that there are scripts being used outside of these three submodules or that the scripts that were previously on these objects were deleted or the GUIDs for the scripts are being broken/unassociated some other way.

**Comment by Guillemsc** [comment]
Thank you very much for this @jeffcampbellmakesgames ! I will look into it as soon as I can :)

**Comment by Guillemsc** [comment]
They were just old scripts that I forgot to remove. Fixed 👍
